#pragma once

#define PROCESS_CREATE_THREAD               0x0002  
#define PROCESS_VM_READ						0x0010
#define PROCESS_VM_OPERATION				0x0008
#define PROCESS_VM_WRITE					0x0020
#define PROCESS_QUERY_INFORMATION			0x0400

const ULONG RemoteMask{ PROCESS_CREATE_THREAD | PROCESS_QUERY_INFORMATION | PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ };